### PR TITLE
Give biglep temporary lotus-docs admin permissions

### PR DESCRIPTION
**Pull request by BigLep**
In support of https://github.com/filecoin-project/lotus-docs/issues/742

### Reviewer's Checklist

- [ ] It is clear where the request is coming from (if unsure, ask)
- [ ] All the automated checks passed
- [ ] The YAML changes reflect the summary of the request
- [ ] The Terraform plan posted as a comment reflects the summary of the request

### CODE REVIEW

**Comment by rjan90** [comment]
While I can't approve this PR, I can 👍 for giving @BigLep temporary access to the lotus-docs repo.

**Review by rjan90 — APPROVED** [review]

**Comment by BigLep** [comment]
@galargh : I'm going to need some help to figure out where the syntax error is that's preventing this from being mergeable.  I couldn't spot any place where teams was empty (which was the clue I have from https://github.com/filecoin-project/github-mgmt/actions/runs/10410558081/job/28832664495?pr=59 ), but maybe my `yq` foo isn't good enough.

**Comment by BigLep** [comment]
@galargh : looking at https://github.com/filecoin-project/github-mgmt/pull/59#issuecomment-2292243131 , I don't know why users other than me are changes here.

**Comment by BigLep** [comment]
> @galargh : looking at [#59 (comment)](https://github.com/filecoin-project/github-mgmt/pull/59#issuecomment-2292243131) , I don't know why users other than me are changes here.

I ran the sync workflow manually and things look to be working.

**Review by rvagg — APPROVED** [review]

**Pull request merged**
